# Generated by Django 3.2.5 on 2021-07-12 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formsdata',
            old_name='date',
            new_name='dob',
        ),
    ]
